--[[
		player
]]--

-- boss spawn 		Vec3(1110, -2050, 0)
-- normal spawn		Vec3(1, 0, 0)
PLAYER_STARTPOSITION = Vec3(1, 0, 0)
PLAYER_SIZE = 5
PLAYER_MAXSPEED = 50
PLAYER_BULLETLIMIT = 25
PLAYER_BULLETDELAY = 0.1
PLAYER_BULLETSPEED = 30
PLAYER_BULLETSIZE = 2
PLAYER_MINIMUMPUSH = 0.05
PLAYER_SHIELDDISTANCE = 2.1 * PLAYER_SIZE
PLAYER_SHIELDDISTANCE_SIDE = 2 * PLAYER_SIZE * 1.05
PLAYER_SHIELDRESTITUTION = 1.0
PLAYER_HP = 100
HEALTH_BAR_LENGTH = 50   -- -(1/3) * CAMERA_Z 
HEALTH_BAR_WIDTH = 5     -- -(1/30) * CAMERA_Z 
RUMBLE_ON = true
CAMERA_Z = -175

--[[
		enemy	
]]--

ENEMY_ARRAYSIZE = 0

-- standard parameters
ENEMY_SIZE = 8
ENEMY_SPEED = 7.5
ENEMY_ROTATIONSPEED = 10
ENEMY_BULLETLIMIT = 10 
ENEMY_BULLETDELAY = 1.0
ENEMY_BULLETSPEED = 15
ENEMY_BULLETSIZE = 3
ENEMY_ATTACKDISTANCE = 100
ENEMY_SCORE_VALUE = 10
ENEMY_HP = 10

-- behaviour types
ENEMY_BEHAVIOURTYPE_MOVE = 0
ENEMY_BEHAVIOURTYPE_TOWER = 1
ENEMY_BEHAVIOURTYPE_BOUNCE = 2
ENEMY_BEHAVIOURTYPE_STALKER = 3
ENEMY_BEHAVIOURTYPE_BOSS = 9

-- shooting directions
ENEMY_SHOOTINGDIR_UP = 0
ENEMY_SHOOTINGDIR_DOWN = 1
ENEMY_SHOOTINGDIR_LEFT = 2
ENEMY_SHOOTINGDIR_RIGHT = 3
ENEMY_SHOOTINGDIR_PLAYER = 4

-- boss condition
BOSS_CONDITION_BEATEN = false

--[[
		healthpack
]]--

HEALTHPACK_SIZE = 8
HEALTHPACK_HPPLUS = 25

--[[
		bullet
]]--

BULLET_LIFETIME = 2

--[[
		utils
]]--

-- etc
PI = 3.14159265359
printTextCalls = 0
printGameplayTextCalls = 0

-- collision filter info
PLAYER_INFO = 0x1
PLAYERBULLET_INFO = 0x3
ENEMYBULLET_INFO = 0x7
ENEMY_INFO = 0xf
OBJECT_INFO = 0x1f

--[[
		main	
]]--

player = {}
enemyArray = {}

GAME_OVER = false
GAME_BEATEN = false