--[[
		player
]]--

-- boss spawn 		Vec3(1110, -2050, 0)
-- normal spawn		Vec3(1, 0, 0)
PLAYER_STARTPOSITION = Vec3(1, 0, 0)
PLAYER_SIZE = 5
PLAYER_MASS = 1.5
PLAYER_LINDAMP = 7.0
PLAYER_MAXSPEED = 50
PLAYER_BULLETLIMIT = 25
PLAYER_BULLETDELAY = 0.1
PLAYER_BULLETSPEED = 30
PLAYER_BULLETSIZE = 2
PLAYER_MINIMUMPUSH = 0.05
PLAYER_SHIELDDISTANCE = 2.1 * PLAYER_SIZE
PLAYER_SHIELDDISTANCE_SIDE = 2 * PLAYER_SIZE * 1.05
PLAYER_SHIELDRESTITUTION = 1.0
PLAYER_HP = 100
HEALTH_BAR_LENGTH = 50   -- -(1/3) * CAMERA_Z 
HEALTH_BAR_WIDTH = 5     -- -(1/30) * CAMERA_Z 
RUMBLE_ON = true
CAMERA_Z = -175

--[[
		enemy	
]]--

ENEMY_ARRAYSIZE = 0

-- standard parameters
ENEMY_SIZE = 8
ENEMY_SPEED = 7.5
ENEMY_ROTATIONSPEED = 10
ENEMY_BULLETLIMIT = 10 
ENEMY_BULLETDELAY = 1.0
ENEMY_BULLETSPEED = 15
ENEMY_BULLETSIZE = 3
BULLET_SIZE_STRONG = 3
BULLET_SIZE_WEAK = 2
ENEMY_ATTACKDISTANCE = 100
ENEMY_SCORE_VALUE = 10
ENEMY_HP = 10

ENEMY_MASS = 1
ENEMY_LINDAMPING = 2.5
ENEMY_RESTITUTION = 0
ENEMY_ANGULARDAMPING = 1
ENEMY_FRICTION = 0 

-- type depending overrides

-- move
ENEMY_TYPE_MOVE_SPEED = 50

-- bounce
ENEMY_TYPE_BOUNCE_MASS = 0.1
ENEMY_TYPE_BOUNCE_LINDAMPING = 0.4
ENEMY_TYPE_BOUNCE_RESTITUTION = 1

-- stalker
ENEMY_TYPE_STALKER_STEERDIST = 10

-- boss
ENEMY_TYPE_BOSS_MASS = 1000
ENEMY_TYPE_BOSS_HP = 150
ENEMY_TYPE_BOSS_SPEED = 300
ENEMY_TYPE_BOSS_BULLETLIMIT = 100 + 60
ENEMY_TYPE_BOSS_BULLETDELAY = 0.2
ENEMY_TYPE_BOSS_BULLESPEED = ENEMY_BULLETSPEED
ENEMY_TYPE_BOSS_BULLETSIZE = 3
ENEMY_TYPE_BOSS_ATTACKDISTANCE = 200
ENEMY_TYPE_BOSS_SCOREVALUE = 1000
ENEMY_TYPE_BOSS_SPECIALATTACKRATE = 30
ENEMY_TYPE_BOSS_NORMALATTACKSCATTER = 40

-- behaviour types
ENEMY_BEHAVIOURTYPE_MOVE = 0
ENEMY_BEHAVIOURTYPE_TOWER = 1
ENEMY_BEHAVIOURTYPE_BOUNCE = 2
ENEMY_BEHAVIOURTYPE_STALKER = 3
ENEMY_BEHAVIOURTYPE_BOSS = 9

-- shooting directions
ENEMY_SHOOTINGDIR_UP = 0
ENEMY_SHOOTINGDIR_DOWN = 1
ENEMY_SHOOTINGDIR_LEFT = 2
ENEMY_SHOOTINGDIR_RIGHT = 3
ENEMY_SHOOTINGDIR_PLAYER = 4

-- boss condition
BOSS_CONDITION_BEATEN = false

--[[
		healthpack
]]--

HEALTHPACK_ARRAYSIZE = 1

--[[
		bullet
]]--

BULLET_LIFETIME = 2
BULLET_MASS = 0.09
BULLET_FRICTION = 0
BULLET_MAXLINVEL = 500
BULLET_LINDAMP = 0

--[[
		utils
]]--

-- etc
PI = 3.14159265359
printTextCalls = 0
printGameplayTextCalls = 0

-- collision filter info
PLAYER_INFO = 0x1
PLAYERBULLET_INFO = 0x3
PLAYERSHIELD_INFO = 0x3f
ENEMYBULLET_INFO_WEAK = 0x7
ENEMYBULLET_INFO_STRONG = 0x7f
ENEMY_INFO = 0xf
OBJECT_INFO = 0x1f

--[[
		main	
]]--

player = {}
enemyArray = {}
healthpackArray = {}

GAME_OVER = false
GAME_BEATEN = false